version: "3"
services:
  client:
    image: one-word-story-client:latest
    depends_on:
      - server
    ports:
      - "4001:4001"
    build:
      context: ./client
      dockerfile: Dockerfile
  server:
    image: one-word-story-server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:      
      - "4000:4000"

