version: "3"
services:
  client:
    image: rishikeshvnair/one-word-story-client:latest
    depends_on:
      - server
    ports:
      - "4001:4001"
  server:
    image: rishikeshvnair/one-word-story-server:latest
    ports:      
      - "4000:4000"

